C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Identity(2,1)*Identity(4,3)
C     
      SUBROUTINE FFFF5P1N_2(F1, F3, F4, COUP,F2)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(6)
      COMPLEX*16 F3(*)
      COMPLEX*16 F4(*)
      COMPLEX*16 TMP5
      TMP5 = (F4(3)*F3(3)+F4(4)*F3(4)+F4(5)*F3(5)+F4(6)*F3(6))
      F2(3)= COUP*(-CI )* TMP5*F1(3)
      F2(4)= COUP*(-CI )* TMP5*F1(4)
      F2(5)= COUP*(-CI )* TMP5*F1(5)
      F2(6)= COUP*(-CI )* TMP5*F1(6)
      END


