C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Identity(2,1)*Identity(4,3)
C     
      SUBROUTINE FFFF5P1N_3(F1, F2, F4, COUP,F3)
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      COMPLEX*16 F1(*)
      COMPLEX*16 F2(*)
      COMPLEX*16 F3(6)
      COMPLEX*16 F4(*)
      COMPLEX*16 TMP6
      TMP6 = (F1(3)*F2(3)+F1(4)*F2(4)+F1(5)*F2(5)+F1(6)*F2(6))
      F3(3)= COUP*(-CI )* F4(3)*TMP6
      F3(4)= COUP*(-CI )* F4(4)*TMP6
      F3(5)= COUP*(-CI )* F4(5)*TMP6
      F3(6)= COUP*(-CI )* F4(6)*TMP6
      END


