ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0D0)
      DOUBLE PRECISION NL
      PARAMETER(NL=0D0)

      DOUBLE PRECISION MDL_MAP,MDL_MMU,MDL_MTA,MDL_MCHI1,MDL_MCHI2
     $ ,MDL_ME,MDL_MP

      COMMON/MASSES/ MDL_MAP,MDL_MMU,MDL_MTA,MDL_MCHI1,MDL_MCHI2
     $ ,MDL_ME,MDL_MP


      DOUBLE PRECISION MDL_WAP,MDL_WCHI2

      COMMON/WIDTHS/ MDL_WAP,MDL_WCHI2


      DOUBLE COMPLEX GC_4, GC_5, GC_6, GC_7, GC_8, GC_9, GC_10, GC_11

      COMMON/COUPLINGS/ GC_4, GC_5, GC_6, GC_7, GC_8, GC_9, GC_10,
     $  GC_11

