ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_epsilon = ', MDL_EPSILON
      WRITE(*,*) 'mdl_Lambda = ', MDL_LAMBDA
      WRITE(*,*) 'mdl_cS = ', MDL_CS
      WRITE(*,*) 'mdl_cPS = ', MDL_CPS
      WRITE(*,*) 'mdl_cV = ', MDL_CV
      WRITE(*,*) 'mdl_cAV = ', MDL_CAV
      WRITE(*,*) 'mdl_cT = ', MDL_CT
      WRITE(*,*) 'mdl_tdip = ', MDL_TDIP
      WRITE(*,*) 'mdl_tcon = ', MDL_TCON
      WRITE(*,*) 'mdl_aEM = ', MDL_AEM
      WRITE(*,*) 'mdl_GF = ', MDL_GF
      WRITE(*,*) 'mdl_Me = ', MDL_ME
      WRITE(*,*) 'mdl_MMU = ', MDL_MMU
      WRITE(*,*) 'mdl_MTA = ', MDL_MTA
      WRITE(*,*) 'mdl_Mchi1 = ', MDL_MCHI1
      WRITE(*,*) 'mdl_Mchi2 = ', MDL_MCHI2
      WRITE(*,*) 'mdl_Mp = ', MDL_MP
      WRITE(*,*) 'mdl_MAp = ', MDL_MAP
      WRITE(*,*) 'mdl_Wchi2 = ', MDL_WCHI2
      WRITE(*,*) 'mdl_WAp = ', MDL_WAP
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aEM = ', MDL_SQRT__AEM
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_gp = ', MDL_GP
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_Lambda__exp__2 = ', MDL_LAMBDA__EXP__2
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'G = ', G
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '

