C     Diagram 1
      DATA MAPCONFIG(1)/1/
      DATA TSTRATEGY(1)/2/
      DATA (IFOREST(I,-1,1),I=1,2)/4,3/
      DATA (SPROP(I,-1,1),I=1,1)/1/
      DATA TPRID(-1,1)/0/
      DATA (IFOREST(I,-2,1),I=1,2)/-1,2/
      DATA (SPROP(I,-2,1),I=1,1)/-13/
      DATA TPRID(-2,1)/0/
      DATA (IFOREST(I,-3,1),I=1,2)/7,6/
      DATA (SPROP(I,-3,1),I=1,1)/999902/
      DATA TPRID(-3,1)/0/
      DATA (IFOREST(I,-4,1),I=1,2)/-3,5/
      DATA (SPROP(I,-4,1),I=1,1)/1/
      DATA TPRID(-4,1)/0/
      DATA (IFOREST(I,-5,1),I=1,2)/-4,-2/
      DATA (SPROP(I,-5,1),I=1,1)/999900/
      DATA TPRID(-5,1)/0/
C     Number of configs
      DATA MAPCONFIG(0)/1/
