ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION MDL_SQRT__AEM,MDL_EE,MDL_GP,MDL_SQRT__2
     $ ,MDL_LAMBDA__EXP__2,AS,MDL_EPSILON,MDL_LAMBDA,MDL_CS,MDL_CPS
     $ ,MDL_CV,MDL_CAV,MDL_CT,MDL_TDIP,MDL_TCON,MDL_AEM,MDL_GF

      COMMON/PARAMS_R/ MDL_SQRT__AEM,MDL_EE,MDL_GP,MDL_SQRT__2
     $ ,MDL_LAMBDA__EXP__2,AS,MDL_EPSILON,MDL_LAMBDA,MDL_CS,MDL_CPS
     $ ,MDL_CV,MDL_CAV,MDL_CT,MDL_TDIP,MDL_TCON,MDL_AEM,MDL_GF


      DOUBLE COMPLEX MDL_COMPLEXI

      COMMON/PARAMS_C/ MDL_COMPLEXI


